version: "3.8"
services:
  postgresql_db:
    image: postgres:16
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: jwt_security
      POSTGRES_USER: mark
      POSTGRES_PASSWORD: password