spring:
  application:
    name: login-registration
  datasource:
    url: jdbc:postgresql://localhost:5435/jwt_security
    password: password
    username: mark
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9999
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    info:
      enabled: true